name: ObbyLang
main: com.clubobsidian.obbylang.plugin.BukkitObbyLangPlugin
version: ${pluginVersion}
author: VirusTotal
api-version: 1.13
softdepend: [DynamicGui, ProtocolLib, SellAllSigns]
#commands:
#  obbylang:
#    description: "ObbyLang command"
#    aliases: [ol]