name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with shadowJar
      run: ./gradlew shadowJar
    - uses: actions/upload-artifact@v2
      with:
        name: obbylang-bukkit
        path: |
          bukkit/build/libs/
    - uses: actions/upload-artifact@v2
      with:
        name: obbylang-bungeecord
        path: |
          bungeecord/build/libs/
    - uses: actions/upload-artifact@v2
      with:
        name: obbylang-velocity
        path: |
          velocity/build/libs/
    - uses: actions/upload-artifact@v2
      with:
        name: obbylang-discord
        path: |
          discord/build/libs/
